lawrencetheabhorrence/hobbysite-C-D-2

forum/admin.py
forum/models.py

**Changelogs**
- Added the models `PostCategory` and `Post` to the forum app.
- Registered the models to the admin site.

Forum models

---

blog/models.py

Blog models

---

blog/admin.py

I was thinking of adding custom views and search but I opted for the default register to align with forums.

blog models admin registered

---

blog/static/style.css
blog/templates/blog/article_detail.html
blog/templates/blog/base.html
blog/templates/blog/index.html

Based on the designs of Mishka Sy and Robynne Gonzales. I Implemented them with CSS.
During testing, I had to use whitenoise in my virtual environment to enable the design.

A complete implementation of the design for blog

---

blog/admin.py

Consistency with forums-admin: added fields, filters, and display

Admin search filters and list

---

commissions/templates/commissions/commissions_detail.html
commissions/templates/commissions/commissions_list.html
commissions/views.py

edited views to use get_list_or_404 and get_object_or_404 
templates/commissions

Commission_views+templates/commissions

---

merchstore/admin.py

Adjusted admin panel customization of admin.py

Adjusted admin panel customization of admin.py

---

commissions/admin.py

Commissions_admin_edit2

---

merchstore/models.py
merchstore/urls.py
merchstore/views.py

Removed pointless try-except, changed num to itemID, made itemID have no default value

Try-except removed, and num turned to itemID with no default value

---

forum/static/forum/style.css
forum/templates/forum/index.html
forum/templates/forum/post_detail.html

From https://github.com/lawrencetheabhorrence/hobbysite-C-D-2/pull/32. Merging styling forum into styling instead first.

Styling forum

---

commissions/templates/commissions/commissions_list.html
commissions/views.py

working commissions url and paths

---

commissions/templates/commissions/commissions_list.html

css hotfix

---

merchstore/templates/merchstore/merchstore_list.html

fixed the missing endblock on list template

merchstore hotfix

---

wiki/static/wiki/style.css
wiki/templates/wiki/article_detail.html
wiki/templates/wiki/article_list.html
wiki/templates/wiki/base.html

Fixed the broken css of Wiki, it should be similar to blog now.

Wiki css hotfix

---

merchstore/static/merchstore/style.css
merchstore/templates/merchstore/merchstore_item.html

merchstore styling fixes

---

commissions/models.py

commissions_models_str

---

.pre-commit-config.yaml
requirements.txt

**Changelogs**
- Adds pre-commit hook to run black/prettifier on all committed files

Black precommit

---

blog/admin.py
blog/urls.py
commissions/views.py
forum/admin.py
forum/models.py
hobbysite/urls.py
wiki/urls.py
wiki/views.py

Incorporated the changes from the midterm project feedback:
I also ran `black` on the whole project to fix the formatting.

Midterm amendments

---

forum/admin.py
wiki/models.py

Edited ArticleCategory model to apply Profile.
Added Comment model. 
Edited registration in forums/admin.py to fix Type error.

Edited Article and ArticleCategory models, added Comment model

---

forum/admin.py

Resolved an previously solved issue #61 that popped up again after some manner of merging into main

Resolved error #61

---

hobbysite/urls.py
templates/registration/register.html
user_management/models.py
user_management/tests.py
user_management/urls.py
user_management/views.py

**Changelogs**
- Implemented registration view
- Had to make a custom form for this aosertnoaesrnoteansoteansoetn

Auth register view

---

commissions/admin.py
commissions/models.py

**Changelogs**
- Added in admin models for commissions app

Commissions admin

---

commissions/templates/commission_update_form.html
commissions/urls.py
commissions/views.py

**Changelogs**
- Implemented class based view for updating commissions

Commissions update view

---

commissions/views.py

- Apparently I forgot to do this
- Shows a commission along with its jobs

Commissions Detail View

---

static/base.css
templates/base.html

**Changelogs**
- Footer was wonky, had to fix it.

fixed the issues with the FOOTER

---

forum/templates/forum/detail.html
forum/templates/forum/index.html
forum/views.py

Updated thread list and thread detail
included the templates

Forum views - thread_list & thread_detail

---

static/base.css
templates/homepage.html

**Changelogs**
- Again, body fix for height
- font fixes

Base styling

---

forum/admin.py

changed the admin to reflect new models

Updated admin.py

---

forum/templates/forum/detail.html

Adjusted code to be more in line with the styling and specs

Updated detail.html

---

forum/templates/forum/thread_create.html
forum/templates/forum/thread_update.html
forum/views.py

added create and update to views and added respective templates

Forums - thread_create & thread_update

---

forum/views.py

removed import for forms in forum

---

static/base.css

**Changelogs**
- Styled the forms

Commissions views

---

commissions/models.py
commissions/static/commissions/commissions_detail.css
commissions/templates/commissions/commissions_detail.html
commissions/templates/commissions/commissions_list.html
commissions/urls.py

**Changelogs**
- implementation of open manpower (open slots)
- manpower is no longer mutated
- fixes in urls and styling for templates

Commissions fix
